#!/usr/bin/env python3
"""Check that README.md's hand-written skill counts match reality.

docs/CATALOG.md and docs/index.html are generated, and `--check` modes prove
they were regenerated. README.md is not generated by anything, so its counts
are maintained by whoever remembers — which is why they sat at 107 while the
library grew to 113. This closes that gap.

    python3 scripts/check_counts.py

Every claim below is a regex with one numeric group. A claim that matches
nothing FAILS rather than passing: a pattern that has silently stopped
matching is a check that has gone blind, which is worse than no check at all,
because the build stays green while nobody is looking.
"""
from __future__ import annotations

import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from _skillmeta import read_text  # noqa: E402
from generate_catalog import CATEGORIES, categorize, collect  # noqa: E402

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
README = os.path.join(REPO, "README.md")

# (human label, pattern with exactly one numeric group)
SKILL_COUNT_CLAIMS = [
    ("headline", re.compile(r"^### (\d+) production-grade Agent Skills", re.M)),
    ("context-cost line", re.compile(r"library of (\d+) costs")),
    ("shields.io badge", re.compile(r"badge/skills-(\d+)-blue\.svg")),
    ("category summary", re.compile(r"\*\*(\d+) skills\*\* across")),
    ("FAQ", re.compile(r"loading (\d+) skills bloat")),
]


def main() -> int:
    skills = collect()
    truth = len(skills)

    text = read_text(README)
    failures: list[str] = []

    for label, rx in SKILL_COUNT_CLAIMS:
        found = rx.findall(text)
        if not found:
            failures.append(
                f"README.md: the {label} claim no longer matches /{rx.pattern}/ — "
                "either the line was reworded (update this pattern) or it was "
                "removed (drop the claim). An unmatched pattern checks nothing."
            )
            continue
        for value in found:
            if int(value) != truth:
                failures.append(
                    f"README.md: the {label} says {value} skills; there are {truth}."
                )

    if failures:
        print(f"FAIL: {len(failures)} stale or blind count claim(s):\n")
        for f in failures:
            print(f"  - {f}")
        print("\nFix the number in README.md, or the pattern in this script.")
        return 1

    cats = sum(
        1
        for c in [x[0] for x in CATEGORIES] + ["Other"]
        if any(categorize(n) == c for n in skills)
    )
    claims = sum(len(rx.findall(text)) for _, rx in SKILL_COUNT_CLAIMS)
    print(f"OK: {claims} README count claim(s) agree with {truth} skills "
          f"across {cats} categories.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
