#!/usr/bin/env bash
# sync-upstream.sh — refresh the pin table in SOURCES.md from this pack's
# upstream, and verify the pack still points at what it says it points at.
#
# web-excellence vendors third-party skills from external repos, so its sync
# clones upstreams. This pack's nine skills are estate-native: their canonical
# copies live in free-skills/ IN THIS REPOSITORY, install.sh reads them from
# there directly, and the pack carries no second copy that could rot. What can
# still drift is the receipt: canon gets edited (that is the point — fixes land
# in free-skills) and the pin table in SOURCES.md goes stale, or a manifest
# entry stops resolving after a rename. This script closes both.
#
#   ./sync-upstream.sh            # verify manifest, rewrite the pin table
#   ./sync-upstream.sh --check    # report drift, change nothing (CI-safe)
#
set -euo pipefail

PACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$(cd "$PACK_DIR/../.." && pwd)"
CHECK_ONLY=0
[ "${1:-}" = "--check" ] && CHECK_ONLY=1

python3 - "$PACK_DIR" "$LIB_DIR" "$CHECK_ONLY" <<'PY'
import hashlib
import os
import re
import sys
from datetime import date

pack_dir, lib_dir, check_only = sys.argv[1], sys.argv[2], sys.argv[3] == "1"
sources = os.path.join(pack_dir, "SOURCES.md")

def entries():
    with open(os.path.join(pack_dir, "manifest.txt"), encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line and not line.startswith("#"):
                yield line

def skill_hash(root):
    """Stable content hash over every file in the skill dir."""
    h = hashlib.sha256()
    n = 0
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for fn in sorted(filenames):
            p = os.path.join(dirpath, fn)
            h.update(os.path.relpath(p, root).encode())
            h.update(open(p, "rb").read())
            n += 1
    return h.hexdigest()[:12], n

errors = []
rows = []
for entry in entries():
    src = os.path.join(lib_dir, entry)
    name = os.path.basename(entry)
    skill_md = os.path.join(src, "SKILL.md")
    if not os.path.isdir(src) or not os.path.isfile(skill_md):
        errors.append(f"manifest entry '{entry}' does not resolve to a skill directory")
        continue
    fm = re.match(r"---\n(.*?)\n---\n", open(skill_md, encoding="utf-8").read(), re.S)
    m = re.search(r'^name:\s*"?([^"\n]+)"?\s*$', fm.group(1), re.M) if fm else None
    if not m or m.group(1) != name:
        errors.append(f"{entry}: frontmatter name {m.group(1)!r} != directory name {name!r}"
                      if m else f"{entry}: no parseable frontmatter name")
        continue
    digest, files = skill_hash(src)
    rows.append((name, entry, digest, files))

if errors:
    for e in errors:
        print(f"!! {e}", file=sys.stderr)
    sys.exit(1)

table = ["| Skill | Canonical source | Content hash | Files | Synced |",
         "|---|---|---|---|---|"]
for name, entry, digest, files in rows:
    table.append(f"| `{name}` | [`{entry}`](../../{entry}) | `{digest}` | {files} | {date.today().isoformat()} |")

doc = open(sources, encoding="utf-8").read()
begin = "<!-- PINS:BEGIN — generated by sync-upstream.sh, do not hand-edit -->"
end = "<!-- PINS:END -->"
block = begin + "\n\n" + "\n".join(table) + "\n\n" + end
new = re.sub(r"<!-- PINS:BEGIN.*?PINS:END -->", lambda _: block, doc, flags=re.S)

if check_only:
    committed = re.search(r"<!-- PINS:BEGIN.*?PINS:END -->", doc, re.S).group(0)
    # Compare everything except the Synced date column, which moves on every run.
    strip = lambda s: re.sub(r"\| \d{4}-\d{2}-\d{2} \|", "| - |", s)
    if strip(committed) != strip(block):
        print("DRIFT: SOURCES.md pin table no longer matches free-skills — run ./sync-upstream.sh")
        for line in table[2:]:
            if line not in committed:
                print(f"  changed: {line.split('|')[1].strip()}")
        sys.exit(1)
    print(f"ok: {len(rows)} pins match canon in free-skills/.")
else:
    open(sources, "w", encoding="utf-8").write(new)
    print(f"Wrote pin table: {len(rows)} skills. Review 'git diff packs/agent-infrastructure' before committing.")
PY
